### ISSUE TITLE
Week 01 - Day 1 - Hello World

### ISSUE THREAD

**Issue by gstark** [GarrettAnderson/assignments#1]
# Hello, World.

In your first assignment you will end up with a web page, no matter how simple, published on the web.

You will create a simple website that will showcase one of your passions. This is not about making the website flashy, but more about focusing on creating a website and learning your new tools.

For this assignment, you will following along with you instructors to complete this homework.

## Objectives

- Get to know your text editor
- Introduce yourself to working on the command line
- Write some HTML
- Publish a web page

## Requirements

- Have `git`, `hub`, `node`, `app-app` installed. We should have done this together in class. Reminder: you only have to install these tools once. 

- All of your HTML (and CSS if you do _epic_ mode) should be formatted cleanly and consistently (use your editor to your advantage).

- If you have experience with existing HTML/CSS frameworks (bootstrap, bulma, etc) you may _not_ use them for these assignments.

### Explorer Mode

- [x] Follow all of the [setup instructions](https://suncoast.io/handbook/tools/assignment-setup).
- [x] Compose a short essay (just a couple paragraphs at most) about a hobby you either enjoy, or would like to learn about. We will be expanding on this page in future assignments, so pick something fun!
- [x] Put your short essay into an HTML page, using appropriate semantic HTML tags. (See the link `HTML Tag Reference` below). Give your webpage a simple header and footer as well.
- [x] Deploy your site.

### Adventure Mode

- [x] Use at least one image somewhere on the page.
- [x] Learn about and investigate the `a` to add (at least 2) more pages to your site.
- [x] Re-deploy your site. 
- [x] [Read more about CSS](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS).

### Epic Mode

- [x] Research the `id` and `class` HTML attributes.
- [x] Use valid CSS to style the page (in the neighborhood of a couple dozen CSS declarations).
- [x] Create a full layout for your page (heading, navigation, sidebar, footer, etc.).
- [x] Use more complex CSS selectors than we covered in class, e.g. attribute selectors or sibling selectors.

## Additional Resources

- [HTML Tag Reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Element)
- [How do HTML Tags work](https://developer.mozilla.org/en-US/Learn/HTML/HTML_tags)
- [Evolution of the Web](http://www.evolutionoftheweb.com)
- [Atom Flight Manual](https://flight-manual.atom.io)
  - [Moving in Atom](https://flight-manual.atom.io/using-atom/sections/moving-in-atom/)
  - [Selecting Text](https://flight-manual.atom.io/using-atom/sections/atom-selections/)
  - [Find and Replace](https://flight-manual.atom.io/using-atom/sections/find-and-replace/)
- [Getting started with VS Code](https://code.visualstudio.com/docs/getstarted/introvideos)
- [Visual Studio Code Basics](https://code.visualstudio.com/docs/introvideos/basics)

## Reading Material

To prep for tomorrow's lesson, you can [read about CSS](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS).

**Comment by GarrettAnderson** [comment]
https://github.com/GarrettAnderson/my-hobbies

**Comment by GarrettAnderson** [comment]
completed the adventure and epic tasks

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![With LASERS](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBGdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8de0b77cb9bd24d453ed6e604c00bc8768a57d5c/BriskEnviousGraywolf.gif)
> &ldquo;With LASERS&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/13)**__
