### ISSUE TITLE
Week 03 - Day 3 - Final

### ISSUE THREAD

**Issue by mdewey** [GarrettAnderson/assignments#11]
# The Final Countdown

This assignment will pull together all the skills and ideas that you have learned for the past three weeks. This project is a bit bigger than usual and will challenge you on the core concepts we have learned over unit-i. For this assignment, you will solve three code katas, and recreate a simple website that uses an API for the data. [This is the website](http://sdg-astro-club.surge.sh/) you will make. This website should be responsive and as close as you can make it.

Since this is a more significant assignment, the pacing is critical.

## Objectives

- Demonstrate basic knowledge of some programming ideas
- using HTML, CSS and JavaScript re-create a simple website
- Recreate [http://sdg-astro-club.surge.sh/](http://sdg-astro-club.surge.sh/)

## Requirements

- Complete the three selected code katas
- Create an SDG Astro Club website using https://sdg-astro-api.herokuapp.com for the data

## Deliverables

- a [gist](https://gist.github.com/) containing the solutions to all three katas
- GitHub repository containing the HTML, JS, and CSS the website
- a URL to the deployed site.

### Explorer Mode

- [x] complete the following katas
  - https://www.codewars.com/kata/filter-out-the-geese
  - https://www.codewars.com/kata/beginner-lost-without-a-map/train/javascript
  - https://www.codewars.com/kata/you-only-need-one-beginner
- [ ] replicate this site exactly (as close as possible) [http://sdg-astro-club.surge.sh/](http://sdg-astro-club.surge.sh/)
  - You should pull data from the API [https://sdg-astro-api.herokuapp.com](https://sdg-astro-api.herokuapp.com)
    - use [https://sdg-astro-api.herokuapp.com/api/Nasa/apod](https://sdg-astro-api.herokuapp.com/api/Nasa/apod) for the NASA picture of the day
    - use [https://sdg-astro-api.herokuapp.com/api/SpaceX/launches/upcoming](https://sdg-astro-api.herokuapp.com/api/SpaceX/launches/upcoming) for the upcoming launch data.
- [ ] deploy your site

## Advice

- Take this in small steps. I would do this in the following order: Katas, HTML, CSS, Picture of the day, and then Upcoming Launches.
- Commit early and commit often.
- Use Font-awesome for the icons. Attach this script to the bottom of your page, and you will be able to use the CSS to create the icons

````html
<script
  defer
  src="https://use.fontawesome.com/releases/v5.5.0/js/all.js"
  integrity="sha384-GqVMZRt5Gn7tB9D9q7ONtcp4gtHIUEW/yG7h98J7IpE3kpi+srfFyyB/04OV6pG0"
  crossorigin="anonymous"
></script>
```
````

**Comment by GarrettAnderson** [comment]
Gist to the kata solutions:

https://gist.github.com/GarrettAnderson/f994702ac4a6f9c75672846fa19a15dd

**Comment by GarrettAnderson** [comment]
https://github.com/GarrettAnderson/nasa-launch-api

**Comment by GarrettAnderson** [comment]
didn't get the countdown feature and still need to refactor.

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBXdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fe539f8c569aecbf6ed495afb3da8e6e3192b8b3/giphy-15.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/80)**__
