### ISSUE TITLE
Week 05 - Day 1-3 - Minesweeper

### ISSUE THREAD

**Issue by mdewey** [GarrettAnderson/assignments#16]
# Minesweeper

In this assignment, you will communicate with a back-end API server to create the user-interface for a [Minesweeper][1] clone. It might help to [familiarize yourself](https://www.youtube.com/watch?v=7B85WbEiYf4) with the game if you've never played it.

[1]: https://en.wikipedia.org/wiki/Minesweeper_(video_game)

## Objectives

- Understand how state drives changes to an interface in React
- Respond to user events in React
- Understand and use REST APIs
- Use React lifecycle methods
- Understand and interpret API documentation
- Use `fetch` or `axios` to perform `POST` request 

## Requirements

Read over the documentation for the API we'll be using:

`https://minesweeper-api.herokuapp.com/`

You will need to interpret the response and render a graphical user interface. The API results include an array of arrays (two-dimensional array), these represent _rows_ and _columns_. These are probably best translated into table rows (`<tr>`) and table data (`<td>`) cells.

Here's an example implementation of this assignment:

![](https://suncoast.io/bomb-sniffer-c9887a428f0d966187200e7a40e3e4b0.gif)

### Explorer Mode

- [x] Create a new game when the page loads, and render it on the screen.
- [x] Style the cells appropriately.
- [x] Left clicking a cell performs the `check` action
- [x] Right/secondary clicking a cell performs the `flag` action
- [x] When the game status changed to `won` or `lost`, show a victory or failure message.

### Adventure Mode

- [x] Before creating the game, prompt the user to choose: _Easy_, _Medium_, or _Hard_ mode.
- [x] Have fun with the styling, make it your own

### Epic Mode

- [ ] Render your victory/failure message as it's own "_screen_".
- [ ] On that screen add a button to restart or play again.
- [ ] Store the current game id in `localStorage`, and render the same game, rather than creating a new one every time (until the player presses the restart button).
- [ ] Add sound effects and animations.

## Additional Resources

- [ ] [React Mouse Events](https://reactjs.org/docs/events.html#mouse-events)

**Comment by GarrettAnderson** [comment]
https://github.com/GarrettAnderson/bomb-sniffer

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Gavin Approved!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cd97f19100495726ff64a3d09a685c898b2e76b3/gavin-lol.gif)
> &ldquo;Gavin Approved!&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/1)**__
