### ISSUE TITLE
Week 01 - Day 2 - Expanding your world

### ISSUE THREAD

**Issue by mdewey** [GarrettAnderson/assignments#2]
# Expanding Your World

In this assignment, you will end up with a simple styled web page, published on the web.

Create a new website that shows some basic styling and formatting using HTML and CSS. This website should help share some information for one of your favorite hobbies.

## Objectives

- Practice using your tools text editor
- Explore new CSS properties
- Publish a web page

## Requirements

- Have `git`, `hub`, and `node` installed. We should have done this together in class.

### Explorer Mode

- [x] Follow all of the setup instructions (See "Assignment Setup").
- [x] Create a new `app-app` project.
- [x] Using CSS, style your page to imitate some of the classic designs of the web. Feel free to make this look as "bad" as you want. Here are some sites to gain inspiration:
  - [10 90s websites designs you won’t believe existed](https://www.justinmind.com/blog/10-90s-websites-designs-you-wont-believe-existed/)
- [x] Add a second page about your hobby with (at least) 2 pictures and with other facts about your hobby.
- [x] Add a menu to your site so a user can go back and forth between the new pages.
- [x] Between the 2 pages, use at least 5 tag selectors, 5 id selectors, and 5 class selectors to style content on your page.
- [x] Deploy your site.

### Adventure Mode

- [x] use pseudo-classes to style elements when you hover the mouse over them
- [x] Add a third page, that has a table. Create this table to have alternating colored rows and a hover over color.
- [x] Make a nav bar that sticks to the top of the page (see the nav bar here for example - https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes)
- [x] Make a footer that always sticks to the bottom of the page

### Epic Mode

- [ ] Explore CSS animations and add some life to your static page. Feel free to really dig into these and try to animate all elements on your page to some extent

### CSS

- [Cool game to learn CSS selectors](https://flukeout.github.io/)
- [Introduction to CSS](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS)
- [Getting Started with CSS Rules](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics#Anatomy_of_a_CSS_ruleset)
- [All the CSS properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference#Keyword_index)
- [pseudo-classes and pseudo-elements](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Pseudo-classes_and_pseudo-elements)
- [http://www.csszengarden.com/](http://www.csszengarden.com/)

### HTML

- [HTML Tags](https://developer.mozilla.org/en-US/Learn/HTML/HTML_tags)
- [Evolution of the Web](http://www.evolutionoftheweb.com)

## Reading Material

To prep for tomorrow's lesson, you can [read about flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/).

**Comment by GarrettAnderson** [comment]
Need to reduce the size of the images on the yoga asanas page to improve load time. Only really got to playing with the slide-in css animation.

**Comment by GarrettAnderson** [comment]
https://github.com/GarrettAnderson/my-hobbies-yoga

**Comment by mdewey** [comment]
Your homework was marked: **Exceeds Expectations**

![Niiiiiiiiice!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBTdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0f7e0d5535291cc82f410da4761392ed248ba5a6/tumblr_inline_odd2x9PvYg1raprkq_400.gif)
> &ldquo;Niiiiiiiiice!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/65)**__
