### ISSUE TITLE
Week 07 - Day 1 - INSERT INTO Student (knowledge) VALUES ('SQL')

### ISSUE THREAD

**Issue by gstark** [GarrettAnderson/assignments#23]
Every application uses data in some way. This will help you set up your development environment as well as get used to querying databases.

## Objectives

* Ensure our Postgres database is installed and working
* Create a database for Employees
* Write some queries to use the database

### Explorer Mode

* [x] Create a database:
  - C#: called `CompanyDatabase`
  - Ruby: called `company_database`
* [x] Create a table:
  - C#: named `Employees`
  - Ruby: named 'employees'
* [x] Add the following columns to the table, Use your best judgement for data types
    - C#
      - Id (Primary Key)
      - FullName
      - Salary
      - Position
      - PhoneExtension
      - IsPartTime
    - Ruby
      - id (Primary Key)
      - full_name
      - salary
      - position
      - phone_extension
      - part_time
* [ ] Create queries that can do the following:
    - [x] Select all columns for all employees
    - [x] Select only the Full Name and Phone Extension for only Full Time employees
    - [x] Insert a new part time employee, as a software developer, part time, with a salary of 450
    - [x] Update all employees that are the cooks to have a salary of 500
    - [x] Delete all employees that have the full name of "Lazy Lynn"
    - [x] Update all employees to be full time
    - [x] Add a column to the table
      - C#: called `ParkingSpotNumber` as a string that up to 10 characters long
      - Ruby: called `parking_spot_number` as a string that up to 10 characters long

* [x] Turn in the above queries as a gist

### Adventure Mode

* [ ] Work on the Koans
* [ ] Work on your final project

### Epic Mode

* [ ] Investigate working with C#/Ruby and Postgres

## Additional Resources

* [https://www.postgresql.org/docs/10/static/index.html](https://www.postgresql.org/docs/10/static/index.html)

## Recommended Practice:

* For more practice, Hackerrank has a [SQL Track](https://www.hackerrank.com/domains/sql)

**Comment by GarrettAnderson** [comment]
https://gist.github.com/GarrettAnderson/aabf36ecbe74ceea15af487467e47b11

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBUZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--395b5be9a8246c8cf018274388a5d5392825ae8e/giphy-2.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/67)**__
