### ISSUE TITLE
Week 07  - Day 3 -  A Whole New World

### ISSUE THREAD

**Issue by mdewey** [GarrettAnderson/assignments#25]
# A Whole New World

Today you learned a new language and will be starting to explore it more in depth in the coming weeks. Like any good craftsman, the first thing you need is to learn your tools. Tonight, you will be setting up your developer environment, creating a simple console application, and writing a short blog.

## Objectives

- Set up your dev machines
- Create a simple console application to ensure your machine is set up correctly
- Write a blog article to practice talking about technology

### .NET Students

- Make sure your [dev env is set up](https://suncoast.io/handbook/curriculum/back-end/full-stack-i/lecture/dotnet/00-env-set-up/)

### Ruby

You should already have Ruby installed.

#### Simple Console Application

- [x] Create a console application that guesses a number that a user has thought of, between 1 and 100. This will use a `binary search`(https://www.programmerinterview.com/index.php/puzzles/minimum-guesses-1-100/) to guess the correct number

- [x] Here is the JavaScript, in the browser, algorithm to follow. Make sure to understand this first before writing new code: [`https://codepen.io/ambethia/pen/KNewBb`](https://codepen.io/ambethia/pen/KNewBb).
      **NOTE** You will be translating this from the event-driven paradigm of HTML to the more procedural paradigm of a console application.
- [x] For Explorer Mode, you do not have to put in a menu or other user experience "nice to haves", focus on the just the core algorithm.

#### Blog

- [ ] We have tackled front end development and are about to tackle a new language. You have grown as a developer and a person in the last 7 weeks. **Pick one topic** and create a blog post about it on Medium.com

* Pick 1 topic technically that we have learned and create a blog post explaining it to a non-technical person.

* Blog about a struggle that you have encountered and overcome during your tenure here so far.

* Pick a new technology that we haven't hit yet (or won't) and create an intro blog for that.

### Adventure Mode

- [ ] Add a nice user experience to the console app. Include features such as
      `Try again` and `Welcome, press enter to start`

### Epic Mode

- [ ] Eventually, we will be using an MVC application structure. To prepare for this, refactor your code to have all your business logic in a separate class and all your console interaction in the main class.

## Additional Resources

- Ruby Resouces:

  - [While Loops](https://learnrubythehardway.org/book/ex33.html)

- .NET
  - [.NET Documentation](https://docs.microsoft.com/en-us/dotnet/)
  - [Lecture notes](https://suncoast.io/handbook/curriculum/back-end/full-stack-i/lecture/dotnet/01-intro-to-c-sharp)

## Reading Material

**Ruby**: Read and work through exercise 14 of [Learn Ruby the Hard Way](https://learnrubythehardway.org/book)

**Comment by GarrettAnderson** [comment]
https://gist.github.com/GarrettAnderson/72265bed40e5d9476e5353c9056d2210

**Comment by GarrettAnderson** [comment]
https://medium.com/@garrettleegrahamanderson/struggles-and-successes-7cffad037569

**Comment by gstark** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBVdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5aaf4fb8aebc193771c4dd6c9823d8f6300ba70b/giphy-7.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/72)**__
