### ISSUE TITLE
Week 07 - Day 4 - Wax On, Wax Off

### ISSUE THREAD

**Issue by gstark** [GarrettAnderson/assignments#26]
# Wax On, Wax Off

> A **koan** is a riddle or puzzle that Zen Buddhists use during meditation to help them unravel greater truths about the world and about themselves. Zen masters have been testing their students with these stories, questions, or phrases for centuries.

As we learn a new language, we need to practice the new ideas, syntax, and paradigms that come what that language. The idea of language Koans helps both beginners and veterans learn the ins and outs of the language.

## Objectives

- Complete your language Koans
- further your capstone project

### .NET Students

- Head to [DotNetCoreKoans](https://github.com/suncoast-devs/DotNetCoreKoans) and follow the directions in the README.md. This will have you fork this repository, clone it and practice the

### Ruby Students

- Head to [Ruby Koans](http://rubykoans.com/) and follow the directions

### Explorer Mode

- [x] Complete the Koans
- [x] Once you are done with you koans, (or need a break), continue to work on the HTML of you capstone.
- [x] Now that you know some SQL and databases, start working on an ERD (Entity relationship diagram) of you capstone projects.

### Adventure Mode

- [ ] (.NET) There are a few Koans that were commented out, comment these in and complete them.

### .NET Students

- Here are some videos about inheritance and interfaces to help gain some more exposure.
  - [Interfaces](https://www.youtube.com/watch?v=neTerkT7LhE)
  - [Inheritance](https://www.youtube.com/watch?v=m0DJIhmUtP8)
  - [Getters & Setters](https://www.youtube.com/watch?v=M0IY3712QCE)

**Comment by GarrettAnderson** [comment]
https://github.com/GarrettAnderson/ruby-koans

**Comment by gstark** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBVUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--03a26be8c53c7287bc40570f4006121a970942ce/giphy-5.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/70)**__
