### ISSUE TITLE
Week 01 - Day 3 - Octdex

### ISSUE THREAD

**Issue by mdewey** [GarrettAnderson/assignments#3]
# Octodex

GitHub has a great mascot called OctoCat. OctoCat even has its own gallery of variations, created by GitHub itself and fans, called [Octodex](https://octodex.github.com).

Unfortunately, the Octodex is not responsive\*! Today, your task is to recreate the layout of The Octodex as closely as possible, but make it responsive. You can use all the tools you have at your disposal to get the job done. Use your browser's Developer Tools to inspect their site to find the exact font sizes and padding amounts.

\* Well, _actually_ it uses javascript to set the number of columns on page load, but we want to see interactive responsiveness when we resize our window!

## Objectives

- Build on your knowledge of HTML & CSS
- Implement a responsive design with media queries
- Implement, from scratch, a given design
- Understand HTML/CSS Layout
- Be able to place elements on a page where you want them.
- Use flexbox techniques layout pages.

## Requirements

- You should strive to implement the design as close as possible, though, especially if you've never touch HTML or CSS before, this can be extraordinarily difficult and will take a lot of practice and mileage.

- **Note**: You should complete at least the tasks given for _explorer_ mode as listed below before turning in the assignment, as well as before attempting _adventure_ or _epic_ modes.

### Explorer Mode

- [x] Recreate the page as closely as you possibly can. Use the same fonts, sizes, and colors. Download some of your favorites
- [x] Use _some_ Octocat images to use in your page (12-16 or so). Your layout should be flexible but doesn't need to _perfectly_ responsive.
- [x] Use flexbox styles to layout the header and the Octocats (hint: check out the `flex-wrap` property).

**TIP** Reminder to breakdown the layout into smaller chunks that are easier to style

## Adventure Mode

- [x] If you're feeling adventurous, use CSS _media queries_ to resize the Octocat containers to look great as a single full-width column on small screens and a nice grid on bigger screens.
- [ ] watch this video to work more with media queries https://www.youtube.com/watch?v=2KL-z9A56SQ

## Epic Mode

- [ ] Go back to your hobby website and update site to be mobile friendly and responsive.

## Additional Resources

- Install the [JSON Viewer Chrome Extension](https://chrome.google.com/webstore/detail/json-viewer/gbmdgpbipfallnflgajpaliibnhdgobh) to make the List of Octocats nicer to read
- [List of Octocats](https://sdg-octodex.herokuapp.com/)
- https://www.youtube.com/watch?v=2KL-z9A56SQ

**Comment by GarrettAnderson** [comment]
https://github.com/GarrettAnderson/octocat

**Comment by mdewey** [comment]
Code overall looks good, make sure to properly format your code. Use your editor to help with that. 

for example, see how your HTML slowly goes further right as your scroll down:https://github.com/GarrettAnderson/octocat/blob/master/public/index.html

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Yas](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--eb161dfb00865249fe33bc4a730793f1eef22b19/neil.gif)
> &ldquo;Yas&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/3)**__
