### ISSUE TITLE
Week 01 - Day 4 - Mock Portoflio

### ISSUE THREAD

**Issue by mdewey** [GarrettAnderson/assignments#4]
# A Portfolio

For your first weekend project, we're going to be starting work on a portfolio website that you can improve over the rest of your career.

![Mockup](https://raw.githubusercontent.com/tiy-tpa-fee/assignments/master/portfolio/mockup.png)

You can find image assets you'll need here:

> https://github.com/tiy-tpa-fee/assignments/tree/master/portfolio/assets

The font used is [Roboto](https://fonts.google.com/specimen/Roboto).

Also, feel free to change it from Jason's picture to a picture of yourself.

## Objectives

- Build on your knowledge of HTML & CSS
- Implement, from scratch, a given design
- Use flexbox techniques layout pages.

## Requirements

- Initially, you should implement the design as close as possible to the mockup. Later, you might choose to fit your personality/style.

- **Note**: You should complete at least the tasks given for _explorer_ mode as listed below before turning in the assignment, as well as before attempting _adventure_ or _epic_ modes.

### Explorer Mode

- [x] Recreate the page as closely as you possibly can. Use the same fonts, sizes, and colors.
- [x] Make sure the site is responsive.
- [x] Deploy your site

### Adventure Mode

- [ ] Take the time to personalize the site with information about yourself, links to your projects, and your pictures.
- [ ] Keep it professional, but make it your own.

### Epic Mode
- [ ] Go back and work on the adventure or epic mode for a past assignment.
- [ ] Start to research [JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript)

**Comment by GarrettAnderson** [comment]
https://github.com/GarrettAnderson/portfolio. Had some challenge with responsive design and how to switch up the layout.

**Comment by GarrettAnderson** [comment]
Still, have some styles to complete for the tablet view. Also, have styles left for the button in order to maintain its position.

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBXZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9ab12a6cb8616834a8b7e838629a5c8c61b5f7a3/giphy-14.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/79)**__
