### ISSUE TITLE
Week 02  - Day 1 - Scoreboard

### ISSUE THREAD

**Issue by mdewey** [GarrettAnderson/assignments#5]
# Score Board

For this assignment, you will be creating a simple interactive scoreboard for your favorite sport.

## Requirements

- Refer to this mockup to design your page:

![](https://raw.githubusercontent.com/suncoast-devs/handbook/master/curriculum/fundamentals/javascript/assignments/assets/scoreboard.png)

- Use the HTML and CSS [here](https://gist.github.com/mdewey/d331c0a449b8e53b4adc472ec0e5a1e8) to jump-start your project.
- A user should be able to update a score and the teams playing.

### Explorer Mode

- [x] Create a new project and implement the design using the given HTML & CSS.
- [x] Assign click events to the `update` buttons to update the corresponding values on the page. The score buttons should adjust the current score by a "hard-coded" value.
- [x] Deploy your site.

### Adventure Mode

- [ ] Implement a Quarter/Period Tracker that would be appropriate for the sport.
- [x] Add some styling to make it more presentable. Have fun with it.
- [ ] Make the layout responsive.

### Epic Mode

- [ ] Add a Timer that counts down automatically and updates the period/quarter appropriately.
- [ ] Save/load the information to local storage.
- [ ] Add CSS to the winning teams score to indicate who is currently winning.
- [ ] Add anything else that your sport would have on its scoreboard (e.g. fouls, sacks, shots on goal, etc.).
- [ ] Improve the UX to help to make scorekeeping by your sport easier.

**Comment by GarrettAnderson** [comment]
https://github.com/GarrettAnderson/scoreboard

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBXZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9ab12a6cb8616834a8b7e838629a5c8c61b5f7a3/giphy-14.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/79)**__
