### ISSUE TITLE
Week 02 - Day 2 - Scoreboard, part 2

### ISSUE THREAD

**Issue by mdewey** [GarrettAnderson/assignments#6]
# Score Board, Part 2

For this assignment, you will be extending and giving your scoreboard some features.

## Requirements

- use last night's project, add a max score, a min score, and a winner.

### Explorer Mode

- [x] Add an `if` statement to stop each team's score from going below 0.
- [x] Add an `if` statement to stop each team's score from going above 21
- [x] When a team gets 21 points, disable the buttons and display a message to the user of who won
- [x] Add a `reset` button that resets the scoreboard back to each team having 0 points and re-enables the buttons

### Adventure Mode

- [x] Add more CSS to the winning teams score to indicate who won.
- [x] Implement a Quarter/Period Tracker that would be appropriate for the sport.
- [x] Add some styling to make it more presentable. Have fun with it.
- [x] Make the layout responsive.

### Epic Mode

- [ ] Add a Timer that counts down automatically and updates the period/quarter appropriately.
- [ ] Save/load the information to local storage.
- [ ] Add anything else that your sport would have on its scoreboard (e.g., fouls, sacks, shots on goal, etc.).
- [ ] Improve the UX to help to make scorekeeping by your sport easier.

### Super Epic mode

- [ ] Start working on creating a two-player Tic Tac Toe.

### Resources

Today's slides: https://slides.com/markdewey-1/if-else/#/

**Comment by GarrettAnderson** [comment]
Had trouble getting the game period counter to increase when a team score is a specific number. I'm not sure if I implemented the Period feature correctly because the period only increases when the button is clicked. Wasn't able to find a way to add a timer.

**Comment by GarrettAnderson** [comment]
https://github.com/GarrettAnderson/scoreboard

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBVQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7b4f1aac5709630cb31aa42251bb0b6a1d5e90eb/giphy-4.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/69)**__
