### ISSUE TITLE
Week 03 - day 1 - Catch your Breath

### ISSUE THREAD

**Issue by mdewey** [GarrettAnderson/assignments#9]
# Catch your Breath

We have been going at a fast pace for the past couple of weeks. Every so often, you need to reflect on how far you have come.

In this assignment, we are going to take a little _code_ break and create a blog post. Writing is a good way to reflect on what you have done and also share some knowledge. The best way to get better at talking about technology is practice. Blog posts are a way to practice that skill.

## Objectives

- Practice talking about technology
- Reinforce a topic we have covered in class

## Requirements

- Create a blog on [Medium](https://medium.com/).

### Explorer Mode

- [x] On [Medium](https://medium.com/), create a blog post that talks about a concept we have gone over in class. This could anything topic from HTML, CSS or JavaScript, or a "lesson learned" from the past couple of weeks. As a challenge, consider picking a topic you think you are weak on. Remember, you are creating a developer-focused blog post.
- [x] Solve this kata: [https://www.codewars.com/kata/volume-of-a-cuboid](https://www.codewars.com/kata/volume-of-a-cuboid) To turn this in, create a [gist](https://gist.github.com) of your code and submit a link to it.
- [x] Submit the link to your published blog post when turning in this assignment.

## Adventure Mode

- [ ] continue to work on blackjack
- [ ] As we progress, we will be using different tools to work our brain. Today, head over to [HackerRank](https://www.hackerrank.com/). This is another tool, like [Codewars](https://www.codewars.com/) to practice our developer skills. As a start, head into the algorithms section, and try [Grading Students](https://www.hackerrank.com/challenges/grading/problem).
- [ ] To turn this in, create a [gist](https://gist.github.com) of your code and submit a link to it.

### Epic Mode

- [ ] Go back and finish up any outstanding work.
- [ ] Go back to a previous assignment and work on it some more. This could be trying to tackle a harder level, working on the UI/UX, refactoring the code to a new idea that we covered (e.g. functions and abstractions), or adding unit tests.
- [ ] To turn this in, link to the other project's repository, and describe what you did.

**Comment by GarrettAnderson** [comment]
Link to Medium blog post: https://medium.com/@garrettleegrahamanderson/revelations-of-leaning-front-end-development-6cb891ba4c39

**Comment by GarrettAnderson** [comment]
https://gist.github.com/GarrettAnderson/b2f48ab5213e38c376cac11d248bc3f8

Had trouble testing the script and submitting the code because of an error on the platform it seems:
Request failed with status code 422
This error was caused due to an issue processing the web request, not because of an issue executing your code. You can retry the request.

**Comment by GarrettAnderson** [comment]
Re-did the kata from the assignment. I realized that I was having issues because I did not log in.

**Comment by GarrettAnderson** [comment]
`var Kata;

Kata = (function() {
  function Kata() {}

  Kata.getVolumeOfCuboid = function(length, width, height) {
    // your code here
    var volume = length * width * height;
    return volume;
  };

  return Kata;

})();`

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![With LASERS](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBGdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8de0b77cb9bd24d453ed6e604c00bc8768a57d5c/BriskEnviousGraywolf.gif)
> &ldquo;With LASERS&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/13)**__
